# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
title: LUFOG
description: '' #>-
email: debugger94@gmail.com
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: 
plugins:
  - jekyll-multiple-languages-plugin
#  - jekyll-feed

encoding: utf-8
include:
  - '.htaccess'
exclude:
  - 'vendor'
  - 'node_modules'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'
# Jekyll Multiple Languages Plugin
languages: ['ru', 'en', 'uk']
exclude_from_localizations: ['assets']

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
